config/routes.rb
Rails.application.routes.draw do
  mount Ckeditor::Engine => '/ckeditor'
  devise_for :users
  get 'welcome/index'  
  get 'welcome/logmein'
  get 'welcome/about'
  
  resources :posts
  resources :listings
  
  root 'welcome#index'
  
  get 'tags/:tag', to: 'posts#index', as: :tag
  get 'listingtags/:tag', to: 'listings#index', as: :listingtag
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/ckeditor/asset.rb
class Ckeditor::Asset < ActiveRecord::Base
  include Ckeditor::Orm::ActiveRecord::AssetBase

  delegate :url, :current_path, :content_type, to: :data

  validates :data, presence: true
end

app/models/ckeditor/attachment_file.rb
class Ckeditor::AttachmentFile < Ckeditor::Asset
  mount_uploader :data, CkeditorAttachmentFileUploader, mount_on: :data_file_name

  def url_thumb
    @url_thumb ||= Ckeditor::Utils.filethumb(filename)
  end
end

app/models/ckeditor/picture.rb
class Ckeditor::Picture < Ckeditor::Asset
  mount_uploader :data, CkeditorPictureUploader, mount_on: :data_file_name

  def url_content
    url(:content)
  end
  
  #https://github.com/galetahub/ckeditor/issues/739
  self.inheritance_column = nil
end

app/models/listing.rb
class Listing < ApplicationRecord
  validates :title, presence: true,
                      length: { minimum: 4 }
  validates :price, presence: true
                      
  self.per_page = 5
  
  acts_as_taggable
end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true,
                      length: { minimum: 5 }
                      
        acts_as_taggable

  self.per_page = 5

  def self.search(search)
    where("title LIKE ? OR text LIKE ?", "%#{search}%", "%#{search}%") 
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: [:index, :show]
  
  def new
    @listing = Listing.new
  end
  
  def index
    if params[:tag]
      @listings = Listing.tagged_with(params[:tag]).paginate(:page => params[:page]).order("created_at DESC")
    else
    @listings = Listing.paginate(:page => params[:page]).order("created_at DESC")
  end
  end
  
  def edit
    @listing = Listing.find(params[:id])
  end
  
  def update
    @listing = Listing.find(params[:id])
    @listing.tag_list.each do | tag | 
      @listing.tag_list.remove(tag)
    end
     @listing.tag_list.add(params["listing"]["tag_list"], parse: true)
 
    if @listing.update(listing_params) 
      redirect_to @listing
    else
      render 'edit'
    end
  end
  
  def show
    @listing = Listing.find(params[:id])
  end
  
  def create
    @listing = Listing.new(listing_params) 
    #acts_as_taggable_on workaround  
    @listing.tag_list.add(params["listing"]["tag_list"], parse: true) 
  
    if @listing.save
      redirect_to @listing
    else
      render 'new'
    end
  end
  
  def destroy
    @listing = Listing.find(params[:id])
    @listing.destroy
    
    redirect_to listings_path
  end
  
  private
  def listing_params
    params.require(:listing).permit(:title, :description, :price)
  end
  
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, only: [:index, :show]
  
  def new
    @post = Post.new
  end
  
  def index
      if params[:search]
        @posts = Post.search(params[:search]).paginate(:page => params[:page]).order("created_at DESC")
      elsif params[:tag]
          @posts = Post.tagged_with(params[:tag]).paginate(:page => params[:page]).order("created_at DESC")
      else
        @posts = Post.paginate(:page => params[:page]).order("created_at DESC")
      end

  end
  
  def edit
    @post = Post.find(params[:id])
  end
  
  def update
    @post = Post.find(params[:id])
    @post.tag_list.each do | tag | 
      @post.tag_list.remove(tag)
    end
     @post.tag_list.add(params["post"]["tag_list"], parse: true)
 
    if @post.update(post_params) 
      redirect_to @post
    else
      render 'edit'
    end
  end
  
  def show
    @post = Post.find(params[:id])
  end
  
  def create
    @post = Post.new(post_params)  
    #acts_as_taggable_on workaround  
    @post.tag_list.add(params["post"]["tag_list"], parse: true)
    
    if @post.save
      redirect_to @post
    else
      render 'new'
    end
  end
  
  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    
    redirect_to posts_path
  end
  
  private
  def post_params
    params.require(:post).permit(:title, :text)
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
        @newposts = Post.order(id: :desc).limit(5)
        @newlistings = Listing.order(id: :desc).limit(3)
  end
  
  def logmein
    render 'logmein'
  end
  
  def about
    render 'about'
  end 
  
  def contact
    render 'contact'
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_flash.html.erb
<div class="row">	
	<div class="col-span-12 alertalert">
		<div class="alert alert-primary" role="alert">
		<div id="flash_messages">
			<% flash.each do |key, value| %>
			<%= content_tag(:div, value, :class => "flash #{key}") %>
			<% end %>
		</div>
		<div>
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<title>Atomic Blackbird</title>
	<%= csrf_meta_tags %>
	<%= csp_meta_tag %>
	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
	<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
	<link href="https://fonts.googleapis.com/css?family=Pacifico" rel="stylesheet">
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.12/css/all.css" integrity="sha384-G0fIWCsCzJIMAVNQPfjH08cyYaUtMwjJwqiRKxxE/rx96Uroj1BtIQ6MLJuheaO9" crossorigin="anonymous">
<meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>	  
		<!--navigation-->
		<nav class="navbar navbar-expand-lg navbar-light">
			<%= link_to('atomic blackbird', welcome_index_path, class: "navbar-brand") %>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav mr-auto">
					<li class="nav-item">
						<%= link_to('Home', welcome_index_path, class: "nav-link") %>
					</li>
					<li class="nav-item">
						<%= link_to('Blog', posts_path, class: "nav-link") %>
					</li>
					<li class="nav-item">
						<%= link_to('About', welcome_about_path, class: "nav-link") %>
					</li>
					<li class="nav-item">
						<%= link_to('For Sale', listings_path, class: "nav-link") %>
					</li>
					<% if user_signed_in? %>
						<li class="nav-link"><%= link_to('Logout', destroy_user_session_path, method: :delete) %>     </li>   
					<% end %>
				</ul>
				<%= form_tag(posts_path, :method => "get", id: "search-form", class: "form-inline my-2 my-lg-0 navbar-form" ) do %>
				    <%= text_field_tag :search, params[:search], placeholder: "Search Posts", class: "form-control mr-sm-2" %>
				    <%= submit_tag "Search", :name => nil, class: "btn btn-outline-dark btn-small my-2 my-sm-0 headerfont"  %>
				<% end %>
			</div>
		</nav>
		<!-- end navigation-->
			<div class="container-fluid">
				<%= render 'layouts/flash' if !flash.empty? %>
					</div> <!--end of container_fluid 1-->
					<div class="container-fluid" style="padding-top: 10px; padding-bottom: 10px; margin-bottom: 0px;">
							<%= yield %>
					</div> <!--end of container_fluid 2 -->

	 
				</body>
				</html>

app/views/listings/_listingform.html.erb
<%= form_with model: @listing, local: true do |form| %>
 
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@listing.errors.count, "error") %> prohibited
        this listing from being saved:
      </h2>
      <ul>
        <% @listing.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
 <p>
   <%= form.label :price %><br>
   <%= form.text_field :price %>
 </p>
 
  <p>
    <%= form.label :description %><br>
	 <%= cktext_area :listing, :description, cols: 40 %>
  </p>
 
 <div class='field'>
     <%= form.label :tag_list, 'Tags (separated by commas)' %><br/>
     <%= form.text_field :tag_list %>
 </div>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/listings/_onelisting.html.erb
<div class="showcard">
	<h2><%= listing.title %></h2>
	<% if listing.updated_at != listing.created_at %>
		<p class="byline"><b>Updated At:</b> <%=listing.updated_at.strftime("%m/%d/%Y %I:%M%p") %></p>
	<% else %>
		<p class="byline"><b>Posted At:</b>  <%=listing.created_at.strftime("%m/%d/%Y %I:%M%p")%></p>
	<%end %>

	<div class="postcontent">
		<%= listing.description.html_safe %>
	</div>


	<% if user_signed_in? %>
	<%= link_to 'Edit', edit_listing_path(listing) %>
	<%= link_to 'Back', listings_path %>
	<%= link_to 'Destroy', listing_path(listing),
	method: :delete,
	data: { confirm: 'Are you sure?' } %>
	<% end %>
</div>

app/views/listings/edit.html.erb
<h1>Edit Listing</h1>

<%= render 'listingform' %>
 
<%= link_to 'Back', listing_path %>

app/views/listings/index.html.erb
<div class="row">
	<div class="col-md-12" style="text-align: center;">
		<h1 class="headerfont">For Sale</h1>
	</div>
</div>
<% if user_signed_in? %>
<li class="nav-link"><%= link_to 'New listing', new_listing_path %> </li>   
<% end %>
<div class="row">
	<div class="col-md-2">
		<div id="tag_cloud" style="word-wrap:break-word;">
			<% tag_cloud Listing.tag_counts, %w{s m l} do |tag, css_class| %>
			<%= link_to tag.name, tag_path(tag.name), class: css_class %>
			<% end %>
		</div>
	</div>
	<div class="col-md-10">
			<%= render partial: "onelisting", collection: @listings, as: :listing %>
	</div>
</div>
<div class="row">
	<div class="col-md-2"></div>
		<div class="col-md-10 paginationcontainer">
			<div class="page_info">
				<%= page_entries_info @listings %>
			</div>
			<div class="pagination">
				<%= will_paginate @listings, :container => false %>
			</div>
		</div>
</div>

app/views/listings/new.html.erb
<h1>New Listing</h1>

<%= link_to 'No, it trash', posts_path %>
<%= render 'listingform' %>

app/views/listings/show.html.erb
<div class="col-md-6 showpost">
<p>
  <strong>Title:</strong>
  <%= @listing.title %>
</p>
 
 <p>
   <strong>Price:</strong>
   <%= @listing.price %>
 </p>
 
<p>
  <strong>Description:</strong>
  <%= @listing.description.html_safe %>
</p>

<p>Tags: <%= raw(@listing.tag_list.map { |t| link_to t, listingtag_path(t) }.join(', ')) %></p> 


<% if user_signed_in? %>
<%= link_to 'Edit', edit_listing_path(@listing) %>
<%= link_to 'Back', listings_path %>
<% end %>
</div>

app/views/posts/_form.html.erb
<%= form_with model: @post, local: true do |form| %>
 
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@post.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @post.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
	 <%= cktext_area :post, :text, cols: 40 %>
  </p>
 
 <div class='field'>
     <%= form.label :tag_list, 'Tags (separated by commas)' %><br/>
     <%= form.text_field :tag_list %>
 </div>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/posts/_onepost.html.erb
<div class="showcard">
	<h2><%= post.title %></h2>
	<p class="byline"><b>Author:</b> <%= post.author %></p>
	<% if post.updated_at != post.created_at %>
		<p class="byline"><b>Updated At:</b> <%=post.updated_at.strftime("%m/%d/%Y %I:%M%p") %></p>
	<% else %>
		<p class="byline"><b>Posted At:</b>  <%=post.created_at.strftime("%m/%d/%Y %I:%M%p")%></p>
	<%end %>

	<div class="postcontent">
			<%= post.text.html_safe %>
	</div>


		<% if user_signed_in? %>
		<%= link_to 'Edit', edit_post_path(post) %>
		<%= link_to 'Back', posts_path %>
		<%= link_to 'Destroy', post_path(post),
		method: :delete,
		data: { confirm: 'Are you sure?' } %>
		<% end %>
</div>

app/views/posts/edit.html.erb
<h1>Edit post</h1>

<%= render 'form' %>
 
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<div class="row">
	<div class="col-md-12" style="text-align: center;">
		<h1 class="headerfont">Blog</h1>
	</div>
</div>
<% if user_signed_in? %>
<li class="nav-link"><%= link_to 'New post', new_post_path %> </li>   
<% end %>
<div class="row">
	<div class="col-md-2">
		<div id="tag_cloud" style="word-wrap:break-word;">
			<% tag_cloud Post.tag_counts, %w{s m l} do |tag, css_class| %>
			<%= link_to tag.name, tag_path(tag.name), class: css_class %>
			<% end %>
		</div>
	</div>
	<div class="col-md-10">
		<%= render partial: "onepost", collection: @posts, as: :post %>
	</div>
</div>
<div class="row">
	<div class="col-md-2"></div>
		<div class="col-md-10 paginationcontainer">
			<div class="page_info">
				<%= page_entries_info @posts %>
			</div>
			<div class="pagination">
				<%= will_paginate @posts, :container => false %>
			</div>
		</div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= link_to 'No, it trash', listings_path %>
<%= render 'form' %>

app/views/posts/show.html.erb
<div class="col-md-6 showpost">
<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @post.text.html_safe %>
</p>

<p>Tags: <%= raw(@post.tag_list.map { |t| link_to t, tag_path(t) }.join(', ')) %></p> 

<% if user_signed_in? %>
<%= link_to 'Edit', edit_post_path(@post) %>
<%= link_to 'Back', posts_path %>
<% end %>
</div>

app/views/welcome/_newlistings.html.erb
<% @newlistings.each do |listing| %>
<div class="indexcontainer">
	<h4><%= link_to listing.title, listing %></h2>
		<% if listing.updated_at != listing.created_at %>
		<p class="byline"><b>Updated At:</b> <%=listing.updated_at.strftime("%m/%d/%Y %I:%M%p") %></p>
		<% else %>
		<p class="byline"><b>Posted At:</b>  <%=listing.created_at.strftime("%m/%d/%Y %I:%M%p")%></p>
		<%end %>
		<p><%= sanitize listing.description.truncate(1000), tags: %w(strong em u i b p) %></p>
		<% if listing.description.length > 0 %>
		<%= link_to "view listing", listing %></p>
		<% end %>
	</div>
	<% end %>

app/views/welcome/_newposts.html.erb
<% @newposts.each do |post| %>
<div class="indexcontainer">
	<h4><%= link_to post.title, post %></h2>
		<% if post.updated_at != post.created_at %>
		<p class="byline"><b>Updated At:</b> <%=post.updated_at.strftime("%m/%d/%Y %I:%M%p") %></p>
		<% else %>
		<p class="byline"><b>Posted At:</b>  <%=post.created_at.strftime("%m/%d/%Y %I:%M%p")%></p>
		<%end %>
		<p><%= sanitize post.text.truncate(1000), tags: %w(strong em u i b p) %></p>
		<% if post.text.length > 0 %>
		<%= link_to "read more", post %></p>
		<% end %>
	</div>
	<% end %>

app/views/welcome/about.html.erb
<div class="row">
	<div class="col-md-1">
	</div>
	<div class="col-md-10 indexcontainer">
		<h2 class="headerfont">About</h2>
		<div class="row">
			<div class="col-sm-3">
				<%= image_tag 'tori_coffee.jpg', class: 'image' %>
			</div>
			<div class="col-sm-9">
				<p>Hi!  My name is Tori Brenneison, and I'm a huge nerd for vintage glassware, golden-age science fiction, and midcentury design.  My boyfriend, Dave, and I live in a 1956 ranch home located in the westside suburbs of Cleveland, OH, USA.  Somewhere along the line it lost its metal cabinets, 9x9 VCT, and wood panelling, but we're constantly working on renovations to bring back some of its original atomic vibe!</p>
				<p>On this blog you'll find:</p>
				<ul>
					<li>Vintage Glass (Pyrex, Fire King, etc.)</li>
					<li>Home Renovation Stories</li>
					<li>Thrift Store Tips & Tricks</li>
				</ul>
			</div>
		</div>
	</div>
	<div class="col-md-1">
	</div>
</div>
<div class="row">
	<div class="col-md-1">
	</div>
	<div class="col-md-10 indexcontainer">
		<h2 class="headerfont">Contact</h2>
		<P>You can follow atomic blackbird on Instagram at @atomic_blackbird, or shoot an email to none@none.com!</p>
	</div>
	<div class="col-md-1">
	</div>
</div>

app/views/welcome/index.html.erb
<div class="row">
	<div class="col-md-6">
		<h2 class="headerfont" style="text-align:center">About</h2>
		<div class="indexcontainer">
			<p><span class="headerfont">Atomic Blackbird</span> is the personal website of midcentury collector Tori Brenneison (and occasionally her boyfriend).  The pair live in a 1956 ranch home in the suburbs of Cleveland, OH and are running out of places to store their Pyrex.  </p>
		</div>
		<h2 class="headerfont" style="text-align:center; padding-top: 10px;">Social</h2>
		<div class="indexcontainer">
			<p style="font-size: 18px;"><i class="fab fa-instagram"></i> @atomic_blackbird</p>
		</div>
				<h2 class="headerfont" style="text-align:center; padding-top: 10px;">Latest Listings</h2>
		<%= render 'newlistings' %>
	</div>
	<div class="col-md-6" style="text-align:center;">
		<h2 class="headerfont">New Posts</h2>
	<%= render 'newposts' %>
	</div>
</div> 

app/views/welcome/logmein.html.erb
<% if user_signed_in? %>
  <li>
  <%= link_to('Logout', destroy_user_session_path, method: :delete) %>        
  </li>
<% else %>
  <li>
  <%= link_to('Login', new_user_session_path)  %>  
  </li>
<% end %>